"""
    Plot returns for Uniswap Liquidity providers
    Requires data files generated by uniswap_returns.py
    These files look like ../data/DAI-USDC_returns.csv
"""

import matplotlib.pyplot as plt
import pandas as pd
import os
import re

data_dir = "../data/"
files = os.listdir(data_dir)

pool_data = []
for f in files:
    m = re.search( r'^(.+)-(.+)_returns.csv', f )
    if m is not None:
        pool_data.append( { 'csv': f, 'token0': m.group(1), 'token1': m.group(2) } )

#Separate plots
for p in pool_data:
    print( f"Plotting {p['token0']} - {p['token1']}" )
    df = pd.read_csv( data_dir + p['csv'] )
    df.day = pd.to_datetime(df.day, format='%Y-%m-%d') #If matplotlib doesn't know they're dates, it makes too many xticks

    plt.plot( df.day, df.profit, label='LP returns' )
    plt.title( f"LP returns for Uniswap v2 {p['token0']} - {p['token1']} pool" )
    plt.xticks(rotation=45)
    plt.xlabel( "" )

#   ax = plt.gca()
#   ax.set_xlim([pd.to_datetime('2022-01-01',format='%Y-%m-%d'),usdc.snapped_at.max()] )

    plt.ylabel( "Annualized returns (%)" )
    
    max_y = df.profit.max()
    min_y = df.profit.min()
    if ['DAI','USDC'] == [ p['token0'], p['token1'] ]:
        plt.axvline(pd.Timestamp('2023-03-10'),linewidth=.5,linestyle='-',color='grey' )
        plt.text( pd.Timestamp('2023-02-01'), .5*max_y, 'SVB Collapse', rotation='vertical', color='grey')
        plt.axvline(pd.Timestamp('2022-11-10'),linewidth=.5,linestyle='-',color='grey' )
        plt.text( pd.Timestamp('2022-10-10'), .5*max_y, 'FTX Collapse', rotation='vertical', color='grey')
#        plt.axvline(pd.Timestamp('2022-11-28'),linewidth=.5,linestyle='-',color='grey' )
#        plt.text( pd.Timestamp('2022-11-05'), .5*max_y, 'BlockFi bankruptcy / DSR increase', rotation='vertical', color='grey')
    if ['USDC','USDT'] == [ p['token0'], p['token1'] ]:
        plt.axvline(pd.Timestamp('2023-03-10'),linewidth=.5,linestyle='-',color='grey' )
        plt.text( pd.Timestamp('2023-02-01'), .1*max_y, 'SVB Collapse', rotation='vertical', color='grey')
        plt.axvline(pd.Timestamp('2022-11-10'),linewidth=.5,linestyle='-',color='grey' )
        plt.text( pd.Timestamp('2022-10-10'), .5*max_y, 'FTX Collapse', rotation='vertical', color='grey')
        plt.axvline(pd.Timestamp('2021-05-05'),linewidth=.5,linestyle='-',color='grey' )
        plt.text( pd.Timestamp('2021-04-01'), -.05*max_y, 'Uniswap v3 Launch', rotation='vertical', color='grey')
    if 'ETH' in [ p['token0'], p['token1'] ]:
        plt.plot( df.day, df.profit - df.BNH, label='Profit relative to Buy and Hold' )
        plt.legend()
#   plt.axvline(pd.Timestamp('2022-05-09'),linewidth=.5,linestyle='-',color='grey' )
#   plt.text( pd.Timestamp('2022-04-09'), 1, 'Terra Collapse', rotation='vertical', color='grey')
#   plt.legend()

    plt.tight_layout() #Prevent the xticks from being cut off

    plt.savefig(f"../figures/{p['token0']}-{p['token1']}.png")
    plt.clf()

#Combined plot
print( 'Making combined plot' )
ax = plt.gca()
for p in pool_data:
    df = pd.read_csv( data_dir + p['csv'] )
    df.day = pd.to_datetime(df.day, format='%Y-%m-%d')

    plt.plot( df.day, df.profit )
    plt.xticks(rotation=45)
    plt.xlabel( "" )

    plt.plot( df.day, df.profit, label=f"{p['token0']}-{p['token1']}" )

    plt.ylabel( "Annualized returns (%)" )

plt.tight_layout() #Prevent the xticks from being cut off

plt.legend()
plt.savefig(f'../figures/combined.png')
plt.clf()
